.\"  @(#)videoconf.1 1.4 92/7/30 SMI
.\"
.\"  Copyright (c) 1992 by INRIA Sophia-Antipolis
.\"
.TH VIDEOCONF 1 "30 July 1992
.SH NAME
.B videoconf
- X11-based videoconferencing tool for Sun SparcStations with  the
VideoPix board. 

.SH SYNOPSIS
.B videoconf
[
.B -o
] [
.B -i
.I multicast address
] [
.B -t
.I ttl
] [
.B -n
.I user name
] [
.B -d
.I display
] [
.I host name
]

.SH DESCRIPTION
.LP
.B videoconf
allows users to conduct multihost audio and video conferences over the
Internet. 
.B videoconf
requires a Sun SparcStation with a VideoPix board and a screen with 8
bits depth. Multihost conferences require that the kernel support
IP multicast.
 On video input, video frames are grabbed by the
.B VideoPix.
No special hardware apart from the SparcStation's build-in audio
hardware is required for audio conference. 
 At start up, a menubar is created with two menus : 
\fIVideo Encoding\fR and \fIAudio Encoding\fR. To select an
option in a menu, click first on the menu, then on the option
desired. (Options for \fIVideo Encoding\fR and \fIAudio
Encoding\fR are described below). Options are written in grey on a
pink background. Once an option is selected, it appears in reverse
video, i.e. in pink on a grey background.
 Video encoding is done according to the
.B H.261
standard (but see BUGS below).

     * \fIVideo Encoding\fR : The video stream can be encoded in either
.B CIF
(352x288 pels) format or
.B QCIF
(176x144 pels). Default format is 
.B CIF.

By default, each packet sent encodes one entire image. To send
smaller packets, choose the
.B One Packet <-> One GOB
option (GOB=Group of Blocks). Then, each packet sent encodes only
one GOB in an image. (Recall that in the H.261 standard, the
maximum number of GOBs in an image is either 12 (CIF) or 3
(QCIF)). Note that the decoder can decode a packet (i.e. part of
an image) before all the packets from that image have been received.
If a GOB doesn't contain any information, its header will be sent 
with the next encoded GOB.

By default, 
.B Privilege Quality
option is selected. You can also privilege rate. In the latter
case, if a lot of information is encoded in an image, an approximate
Cosine transform will be used, reducing the quantity of
information sent by the coder. Furthermore, the encoder increases
the value of the quantizer (and hence reduces the output rate of
packets) whenever packets are lost.


     * \fIAudio Encoding\fR : The audio stream can be encoded with either
.B PCM (64 kb/s)
,
.B ADPCM (32 kb/s)
or
.B VADPCM 
(variable rate ADPCM) compression techniques.
The ADPCM 32 kb/s codec is based on Jack Jansen's codec
(Jack.Jansen@cwi.nl) with modifications to support the
SparcStation's audio format. Note that the state record is reset with
each packet to tolerate packet loss. 
 The VADPCM codec is a variant of the ADPCM codec, in which Huffman codes
are used to encode ADPCM coefficients.

.B videoconf
currently displays the list of active audio/video conference sides
with your site appearing first. When a site is sending audio or
video data, a button appears on the right side with the label
"Yes" or "No". "Yes" means that audio/video data from that site is
decoded. "No" means that audio/video data is dropped.
To add or delete decoding sites, click on the corresponding buttons.
By default, audio information from remote sides is automatically decoded
and video information is dropped.

.SH OPTIONS
.LP
.TP 10
.B -o
By default, QCIF video images are doubled in order to have a CIF
display. This option forces 
.B videoconf
to display video sequences in their original format.
.TP 10
.B -i \fImulticast address\fR 
Change the multicast address. You can specify an IP multicast
address in the range 224.0.0.0 to 239.255.255.255. By default this
address is read in the default file 
.B .videoconf.default
or if it doesn't exist is set to 224.8.8.8.
.TP 10
.B -t \fIttl\fR
Set the multicast time-to-live to \fIttl\fR.
Default value is 4.
.TP 10
.B -n \fIuser\fR
Override your unix user name with \fIuser\fR
.TP 10
.B -d \fIdisplay\fR
Specifies the server to connect to; see \fIX(1)\fR.
.TP 10
.B  \fIhost name\fR
Put 
.B videoconf
in 
.B unicast
mode. Audio and video data are sent to the host
selected. In this mode, you cannot decode your own data unless the
\fIhost name\fR is set to your actual host name. Note that you can
receive data from several sites.


.SH CCITT RECOMMENDATION H.261
This recommendation describes the video coding and decoding methods for the 
moving picture component of audiovisual services at the rates of 
.B p x 64 kbits/s, 
where p is in the range 1 to 30. Two pictures scanning format are specified. 
In the first format 
.B CIF,
the luminance sampling structure is 352 pixels per line, 144 lines per
picture in an orthogonal arrangement. Sampling of each of the two color
difference components is at 176 pixels per line, 144 lines per picture,
orthogonal. 
The second format
.B
QCIF,
has half the number of pixels and half the number of lines stated above.

.SH NOTES
.LP
The 
.B VideoPix 
card is designed to be used with SparcStations IPC, 1, 1+, 2, IPX.

The transmitted bit-stream doesn't contain a BCH11 (511,493) forward error
correction code.

The
.B OSF/MOTIF
toolkit is used to provide the graphical user interface.
.SH BUGS
This software release only encodes video in grayscale mode.

Motion vectors are not implemented.

All the blocks are encoded in INTRA mode, thereby limiting the effect of
packet loss. A Coded Block Pattern (CBP) is added in each
macroblock so as not to necessarily encode all the blocks in a macroblock.

.SH "SEE ALSO"
.I "Using VideoPix",
.I CCITT Recommendation H.261,
.BR h261_decode(1),
.BR h261_encode(1),
.BR ADPCM(2),
.BR X(1).

.SH "AUTHOR"
Thierry Turletti (turletti@sophia.inria.fr) of RODEO Project, INRIA Sophia
Antipolis, FRANCE.
