.\"  @(#)ivs_replay.1 2.2 93/1/21 SMI
.\"
.\"  Copyright (c) 1992 by INRIA Sophia-Antipolis
.\"
.TH IVS_REPLAY 1 "21 January 1993
.SH NAME
.B ivs_replay
\- play an audio/video ivs encoded clip.

.SH SYNOPSIS
.B ivs
[
.B \-double
] 
.I clipname


.SH DESCRIPTION
.LP
This command plays the audio/video ivs encoded clip to the audio
device and displays video in a window on the screen.

.SH OPTIONS
.LP
.TP 10
.B \-double
In this mode, QCIF video images are expanded in order to have a CIF
display. 
.TP 10
.I clipname
Specifies the ivs encoded clip to play.


.SH "SEE ALSO"
.BR ivs(1),
.BR ivs_replay(1).

.SH "AUTHOR"
Thierry Turletti (turletti@sophia.inria.fr) of RODEO Project, INRIA Sophia
Antipolis, FRANCE.
